In [9]:
# ndarray의 데이터 타입
import numpy as np

array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) # 차원과 크기를 튜플 형태로 나타냄
print('\n')

array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)
print('\n')

array3 = np.array([1, 2, 3])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)
print('\n')

print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))
print('\n')

list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


array3 type: <class 'numpy.ndarray'>
array3 array 형태: (3,)


array1: 1차원, array2: 2차원, array3: 1차원


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [15]:
# arange, zeros, ones: ndarray를 편리하게 생성
import numpy as np

sequance_array = np.arange(10)
print(sequance_array)
print(sequance_array.dtype, sequance_array.shape)
print('\n')

zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)
print('\n')

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [26]:
# reshape: ndarray의 특정 차원 및 크기로 변환
import numpy as np

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(-1, 5)
print('array2:\n', array2.shape)

array3 = array1.reshape(5, -1)
print('array3:\n', array3.shape)

# array4 = array1.reshape(-1, 4)  # Error: cannot reshape array of size 10 into shape (4)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 (2, 5)
array3:
 (5, 2)


In [38]:
# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱

## 단일 값 추출
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:', value)
print(type(value))
print('\n')

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])
print('\n')

# 단일 인덱스를 이용해 ndarray 내의 데이터 값도 간단히 수정 가능
array1[0] = 9
array1[8] = 0
print('array1:', array1)
print('\n')

# 다차원 ndarray에서 단일 값 추출
array1d = np.arange(start=1, stop = 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('row=0, col=0) index 가리키는 값:', array2d[0,0])
print('row=0, col=1) index 가리키는 값:', array2d[0,1])
print('row=1, col=0) index 가리키는 값:', array2d[1,0])
print('row=2, col=2) index 가리키는 값:', array2d[2,2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


array1: [9 2 3 4 5 6 7 8 0]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
row=0, col=0) index 가리키는 값: 1
row=0, col=1) index 가리키는 값: 2
row=1, col=0) index 가리키는 값: 4
row=2, col=2) index 가리키는 값: 9


In [44]:
## 슬라이싱
import numpy as np

array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))
print('\n')

array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)
print('\n')

# 2차원 ndarray에서 슬라이싱으로 데이터에 접근
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

[1 2 3]
<class 'numpy.ndarray'>


[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [50]:
## 팬시 인덱싱
import numpy as np

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


In [59]:
# 불린 인덱싱
import numpy as np

array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

# 조건식만 할당해도 False, True로 이뤄진 ndarray 객체가 반환됨
# print 시 True 값이 있는 인덱스 위치의 데이터만 반환
array1d > 5
print('\n')

boolean_indexes = np.array([False, False,False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)
print('\n')
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


불린 인덱스로 필터링 결과: [6 7 8 9]


일반 인덱스로 필터링 결과: [6 7 8 9]


In [67]:
# 행의 정렬 - sort()와 argsort()
import numpy as np

org_array = np.array = ([3, 1, 9, 5])
print('원본 행렬:',org_array) 
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2 = org.array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3, 1, 9, 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3, 1, 9, 5]


NameError: name 'org' is not defined